### ISSUE TITLE
Analysis the gap between HEFPI and new time series generated

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#13]
1. To compare with the current version HEFPI with the newly generated time series, document the differences. Data points interested: the gaps occurred in what country, year, and datapoint. @robin-wang please iterate or expand here if there's more clarity in the future. 
2. Timeline: to be updated when there's more clarity @robin-wang

**Comment by wengxyu1030** [comment]
@yixinluo304 would kindly help on this issue. To achieve goal 1 listed above, we need to firstly identify the gaps between the HEPI data and the microdata set generated in the new templates (the time series data produced in this repo). 

**Some introduction below to give you more context:**

Background: HEFPI data is produced by the WB team that is already published. The dataset is tracking **the same range of indicators**, but the data was generated in a template that is not sufficient or flexible enough. The new templates are designed, the team used these new templates reproducing these indicators in a more standard way. The output collapsed to the time series data you have helped prepare. 

Objective: As part of the quality checking procedure, we want to make sure that the data generated from the new templates are consistent with the previously produced HEFPI data. To achieve this, we need (i) firstly to identify the difference/gaps, and (ii) to figure out what caused the difference. 

Methodology: 
1. Identify missing data points: data points that are available in HEFPI data but **not** in time series.
2. Identify abnormal data: data points that are distinctively different than what's in HEFPI data. We defined an algorithm to set the acceptable range of data difference by the data absolute value. Please refer to this section in the code for quality checking:  https://github.com/wengxyu1030/DHS-Recode-VII/blob/ec0b97664b978a2a0a7c8b7ede2083631f2ec140/Quality_control.do#L210. More specifically, you can use the code from line 219 to 228, which defined how we identify and flag abnormal data. 

Task: 
1. Make sure https://github.com/wengxyu1030/UHC-Time-Trend/blob/b9f1fc575ed4c28e9e3ce9db5da267f90dfee65c/03_time_trend_DW.do can successfully run with the DHS and MICS time series generated by you.
2. In the dofile above, add code to Identify the missing or abnormal data in the time series: 
- generate variable _gap_hefpi_ (please refer to the code mentioned in section Methodology 2).
- generate variable _gap_mis_  to identify the missing data defined in section Methodology 1.

3. Produce an output filter out all missing data ( _gap_mis_) and abnormal data (_gap_hefpi_) points identified. And save it as an excel sheet in the folder https://github.com/wengxyu1030/UHC-Time-Trend/tree/main/results.

**Comment by jianingwwww** [comment]
> @jianingwwww would kindly help on this issue. To achieve goal 1 listed above, we need to firstly identify the gaps between the HEPI data and the microdata set generated in the new templates (the time series data produced in this repo).
> 
> **Some introduction below to give you more context:**
> 
> Background: HEFPI data is produced by the WB team that is already published. The dataset is tracking **the same range of indicators**, but the data was generated in a template that is not sufficient or flexible enough. The new templates are designed, the team used these new templates reproducing these indicators in a more standard way. The output collapsed to the time series data you have helped prepare.
> 
> Objective: As part of the quality checking procedure, we want to make sure that the data generated from the new templates are consistent with the previously produced HEFPI data. To achieve this, we need (i) firstly to identify the difference/gaps, and (ii) to figure out what caused the difference.
> 
> Methodology:
> 
> 1. Identify missing data points: data points that are available in HEFPI data but **not** in time series.
> 2. Identify abnormal data: data points that are distinctively different than what's in HEFPI data. We defined an algorithm to set the acceptable range of data difference by the data absolute value. Please refer to this section in the code for quality checking:  https://github.com/wengxyu1030/DHS-Recode-VII/blob/ec0b97664b978a2a0a7c8b7ede2083631f2ec140/Quality_control.do#L210. More specifically, you can use the code from line 219 to 228, which defined how we identify and flag abnormal data.
> 
> Task:
> 
> 1. Make sure https://github.com/wengxyu1030/UHC-Time-Trend/blob/b9f1fc575ed4c28e9e3ce9db5da267f90dfee65c/03_time_trend_DW.do can successfully run with the DHS and MICS time series generated by you.
> 2. In the dofile above, add code to Identify the missing or abnormal data in the time series:
> 
> * generate variable _gap_hefpi_ (please refer to the code mentioned in section Methodology 2).
> * generate variable _gap_mis_  to identify the missing data defined in section Methodology 1.
> 
> 3. Produce an output filter out all missing data ( _gap_mis_) and abnormal data (_gap_hefpi_) points identified. And save it as an excel sheet in the folder https://github.com/wengxyu1030/UHC-Time-Trend/tree/main/results.

Hi Aline, 

Thank you for sharing with me the latest progress of the project! But I might not be available recently due to my schoolwork, which I have mentioned to Robin. Could you kindly assign this task to others? 
I’m so sorry if that causes you trouble. Please let me know if you need any supportive materials from me.

Thanks,
Jianing

**Comment by yixinluo304** [comment]
Many thanks to @wengxyu1030 and @robin-wang for taking the time to solve the quality detection problem of flag_hefpi today, and I've attached a screenshot to this comment so we can easily check it later.
<img width="948" alt="2022-01-26" src="https://user-images.githubusercontent.com/93497693/151105910-69f2d51e-96ef-445f-852f-a3146f37d83a.png">

**Comment by wengxyu1030** [comment]
@robin-wang and @yixinluo304 there was issue where hefpi data merged are missing for DHS and MICS. I just solved these issue and the latest data are updated in the OneDrive _MEASURE UHC DATA - Sven Neelsen's files\STATA\DATA\SC\ADePT READY\MICS\Time_Series\FINAL_.

The missing report is below for your reference:

![image](https://user-images.githubusercontent.com/63058112/152733280-d5f25a7d-fa73-41fd-bceb-a016916c0dc8.png)


@yixinluo304 Please note that the working directory is adjusted in the template, maybe that's why the previous issue occurred.

**Comment by robin-wang** [comment]
> @robin-wang and @yixinluo304 there was issue where hefpi data merged are missing for DHS and MICS. I just solved these issue and the latest data are updated in the OneDrive _MEASURE UHC DATA - Sven Neelsen's files\STATA\DATA\SC\ADePT READY\MICS\Time_Series\FINAL_.
> 
> The missing report is below for your reference:
> 
> ![image](https://user-images.githubusercontent.com/63058112/152733280-d5f25a7d-fa73-41fd-bceb-a016916c0dc8.png)
> 
> @yixinluo304 Please note that the working directory is adjusted in the template, maybe that's why the previous issue occurred.

Hooray!!!

**Comment by yixinluo304** [comment]
> @robin-wang and @yixinluo304 there was issue where hefpi data merged are missing for DHS and MICS. I just solved these issue and the latest data are updated in the OneDrive _MEASURE UHC DATA - Sven Neelsen's files\STATA\DATA\SC\ADePT READY\MICS\Time_Series\FINAL_.
> 
> The missing report is below for your reference:
> 
> ![image](https://user-images.githubusercontent.com/63058112/152733280-d5f25a7d-fa73-41fd-bceb-a016916c0dc8.png)
> 
> @yixinluo304 Please note that the working directory is adjusted in the template, maybe that's why the previous issue occurred.

Well noted, thanks!!

**Comment by robin-wang** [comment]
The code-snippet below contains the updated methodology for flagging outliers in the benchmarking exercise. Propose to proceed with this flagging indicator.

For details, go to 0305 Updated QC Report, end of file section
https://docs.google.com/document/d/1WLE67py5vMWRXLt2XU_2Cse19KHmd_4do9JyK35WPfU/edit#

---

gen flag_hefpi_march = 0 
replace flag_hefpi_march = 1 if ((gap_hefpi >20 | gap_hefpi < -20 )& value_hefpi<=5)
replace flag_hefpi_march = 1 if ((gap_hefpi >15 | gap_hefpi < -15 )& inrange(value_hefpi,5,10))
replace flag_hefpi_march = 1 if ((gap_hefpi >12 | gap_hefpi < -12 )& inrange(value_hefpi,10,20))
replace flag_hefpi_march = 1 if ((gap_hefpi >10 | gap_hefpi < -10 )& inrange(value_hefpi,20,40))
replace flag_hefpi_march = 1 if ((gap_hefpi >8 | gap_hefpi < -8 )& inrange(value_hefpi,40,50))
replace flag_hefpi_march = 1 if ((gap_hefpi >7 | gap_hefpi < -7 )& inrange(value_hefpi,50,60))
replace flag_hefpi_march = 1 if ((gap_hefpi >6 | gap_hefpi < -6 )& inrange(value_hefpi,60,70))
replace flag_hefpi_march = 1 if ((gap_hefpi >5 | gap_hefpi < -5 )& inrange(value_hefpi,70,80))
replace flag_hefpi_march = 1 if ((gap_hefpi >4 | gap_hefpi < -4 )& inrange(value_hefpi,80,100))

replace flag_hefpi_march=0 if value==. & value_hefpi==.
replace flag_hefpi_march=2 if value!=. & value_hefpi==.

---

<img width="566" alt="Screenshot 2022-03-05 at 4 32 46 PM" src="https://user-images.githubusercontent.com/32467176/156875436-7dec9b9b-b66b-4351-a992-50036c532dec.png">


<img width="727" alt="Screenshot 2022-03-05 at 3 20 53 PM" src="https://user-images.githubusercontent.com/32467176/156873064-75e095af-fdf3-4a7f-a299-76c725660860.png">
