### ISSUE TITLE
Update Quality Checking Dashboard

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#17]
Generate annualized growth rate in the time-series data and update to the dashboard. 
1. Please update the 03_dofile accordingly for the annualized growth rate: growth_rate. (you can refer to other statistics generated in the same dofile, for example, the standard deviation).
2. Please update the output time-series with this new variable in the dashboard. 
3. Please create the growth rate filter in the tableau dashboard.

**Comment by wengxyu1030** [comment]
Thanks for @yixinluo304 's update and @robin-wang 's review of the pull request #19 ad #18 . Considering we are putting this as a filter in the dashboard, when we filter the growth rate in the dashboard, we also want to see how the benchmarked data looks like (other source). So let's add the annualized growth rate value calculated from source "my" also to other source "hefpi" and "dhs", so when filter, we can see data for same variable from different sources. Just like the logic for gap_hefpi in the 03 dofile, where that's the flagged data for source "my", but when filter, we still want to see the value for other sources. 

Please let me know if there's further question.

**Comment by wengxyu1030** [comment]
Hi @yixinluo304 and @robin-wang , to clarify the above. We are not trying to calculate different growth rates for different sources of data ("source"). But just to copy the growth rate calculated when "source" is "my" to other sources of same data (make sure the filter works).

More specifically, please see how we did this for the variable my_sd, in row 90-91. 

https://github.com/wengxyu1030/UHC-Time-Trend/blob/8265a1a75d3be84337367dfe5ae580c7d08f78f2/03_time_trend_DW.do

**Comment by yixinluo304** [comment]
Many thanks to @wengxyu1030  for pointing out the problem and really appreciate @wengxyu1030  and @robin-wang‘s detailed information. Here is the pull request #20.

Please help to review the code and let me know if there are any changes required.

**Comment by wengxyu1030** [comment]
Hi @yixinluo304 , thanks for your update. I made some adjustments in pull request #20 and merged accordingly. More specifically:

1. Adjusted the working directory to be consistent with the folder structure set up. 
2. Corrected the sorting issue, previous only sorting by year is not sufficient, should sorting country **varname** year to make the calculation works. 
2. Adjusted the algorithm: select the max annualized growth rate to be the indicator (it's advised by WB, sorry for the adjustment).

Please run this latest version of code and update the data and filter in the dashboard accordingly. Thanks again for your kind support. 

Regards, 
Aline

**Comment by yixinluo304** [comment]
File uploaded.  #21 
Thank you @wengxyu1030 for the updated information!

**Comment by wengxyu1030** [comment]
Hi @yixinluo304 ,

Thanks for the updated quality checking dashboard, it works well on my end! We adjusted the dashboard a little bit and will wait for feedback from the task manager. 

At the same time, I noticed that there are issues with the country name in the final data (variable _country_), where the country name is not consistent for the countries' names with more than one word. For example, Kyrgyz Republic is sometimes written as KyrgyzRepublic and the statistics (**growth rate, standard deviation, etc.**) would be calculated separately, and the dashboard will present them as different categories. 

To identify these issue: try `tab country` command and you will see the duplicates.

Could you kindly identify these issues and correct them in the 03 dofile? I would recommend taking out the spaces in the country names, in this case, Kyrgyz Republic should all be KyrgyzeRepublic. 

Regards, 
Aline

**Comment by yixinluo304** [comment]
Hi @wengxyu1030 ,

The spaces between the names of the countries have been adjusted. Following the same logic, I have named Congo, Congodr and Dem. Rep. Congo consistently as Congodr (thanks to @robin-wang for the advice).  #21 

At the same time, I noticed that the adjusted dataset doesn't seem to work with the previous Tableau dashboard. 

Best，
Yixin

**Comment by wengxyu1030** [comment]
The dataset is updated and it fitted to the Tableau dashboard updated to the repo now.
