### ISSUE TITLE
Issue on unit and value 

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#24]
Thanks to @robin-wang ,there are issues identified at the quality checking stage on the unit and value: 

**Inconsistent Unit:** 
Might have values as 0.xx rather than xx in percentage number (shown as 0.76 for example) : c_facdel, Tajikistan 2012
**Potential missing values** 
counted as 100 / 1 (need to check): c_vaczeo, Togo & Trinidad and Tobago

**Comment by wengxyu1030** [comment]
@yixinluo304 Could you kindly help us identify the issue above by checking the collapsed time series produced by the 03 dofile? The intermediate deliverable could be identifying the surveys and indicators with these issue to share with us, then check what caused the issue (the collapsing stage or the microdata coding stage)

**Comment by yixinluo304** [comment]
Hi @wengxyu1030 @robin-wang , inside the zip are the dta. files of **inconsistent unit** (obs. 1,471) and **potential missing values** (obs. 171). Please check them as a reference.
[Issue on unit and value.zip](https://github.com/wengxyu1030/UHC-Time-Trend/files/8126485/Issue.on.unit.and.value.zip)

**Comment by wengxyu1030** [comment]
Thanks @yixinluo304 , this is very helpful! I will look at them and see how to fix these issues.

**Comment by wengxyu1030** [comment]
For cases where the value is lower than 0, it's not mistaken by unit but by coding issue for the specific countries, these can be identified by the outlier filter and can be classified as abnormal fluctuation of time-series. @robin-wang

**Comment by wengxyu1030** [comment]
For those that are 100, 

1. There are some of them can be identified as mistaken from the comparison with the benchmarks. 
2. For those without benchmarks, some can be identified in the outlier filter. 
3. But still, there are cases where neither outlier filter or benchmarks can help, might need lose the outlier threshold. @robin-wang

**Comment by robin-wang** [comment]
I am circling back to this discussion. Now that we are identifying problematic data points with a combined solution (benchmarking + time series).

I feel what we were looking at could be wrapped into the updated approach. For those that are 100, would you agree that they don't pose a separate challege for our quality checking process? Thanks!!! @wengxyu1030

**Comment by wengxyu1030** [comment]
For data points in category 3, separate efforts are needed.
