### ISSUE TITLE
Identify and classify the outliers

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#26]
thanks for @robin-wang comments, below are the outliers identified by the growth rate and standard deviation (third quartile+ 1.5 IQR), with narrowed downed focus on the 25 indicators. 
![Time Trend (outlier)](https://user-images.githubusercontent.com/63058112/155046228-25551e24-1ece-4d6a-ba3c-753bc0ffa703.png)

**Comment by wengxyu1030** [comment]
See the update in code and dashboard in the commit: https://github.com/wengxyu1030/UHC-Time-Trend/commit/350b33406b3f97bdd6d785220356437b4152c650

**Comment by robin-wang** [comment]
Absolutely brilliant!!!!!

**Comment by wengxyu1030** [comment]
Based on this figure, let's decide on how to deal with them?

**Comment by robin-wang** [comment]
Hey Aline, thanks much.
I think this is narrowed-down enough, save one more additional layer of filter, whether the data points have benchmarks. Recall we had a visualisation like the one below, if the identified outliers have then been validated by the benchmarking exercise, we could perhaps filter them out? Not sure how much good this does, nor how intensive the work is. 

If too complicated to implement, I think we could ask Yixin to jump in. 

<img width="1027" alt="Screenshot 2022-02-22 at 10 57 46 AM" src="https://user-images.githubusercontent.com/32467176/155054890-2012d5b0-e187-4d5e-bff5-f6b016cb0a46.png">

**Comment by wengxyu1030** [comment]
Hi @robin-wang , 

Thanks for the email, the dashboard is as it is on tableau public and has the visualization you pointed out with the benchmark. 

Yes, on deciding about whether to recode the abnormal time sereis survey, one could factor in the benchmarks. We already flagged the problematic data points in comparison with hefpi and dhs data, which depend on the thresholds you are working on. Once the flagged data points are agreed upon, they could be easily merged and filtered. 


Regards, 
Aline

**Comment by wengxyu1030** [comment]
Incorporated all the comments above, the updated version is here @robin-wang https://public.tableau.com/app/profile/data.whale/viz/tim_trend_viz_story/Story1,
with the code updated in the commit: https://github.com/wengxyu1030/UHC-Time-Trend/commit/cce8e2722350a601c4b42f19c8b69dfc6d996307
Methodology updated here: https://docs.google.com/document/d/1WLE67py5vMWRXLt2XU_2Cse19KHmd_4do9JyK35WPfU/edit#

Several changes made:
1. The scope of the dashboard only focusing on the important indicators identified by @robin-wang and WB team. 
2. The time series outliers are defined by the max annual growth rate Q3+1.5IQR.
3. Identified the flagged data points from benchmarking with previous published HEFPI data, by the size of the line chart marks.
