### ISSUE TITLE
w_CPR

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#33]
**Congodr**

2001-2013 is consistent with HEFPI. The definition of the methods and missing conditions are accurate for 2017. Please refer to the benchmark, code, and definition below. However, I am confused about the coding logic, which is problematic in the loop. The code is loop around the answers to different methods, and replaces w_CPR is 1 if the modern method is used, replace w_CPR  to missing if the answer is missing. However, this logic is highly dependent on the variable order in the loop, if the answer for method 1 is confirmed as 1 however for method 5 is missing, the w_CPR should be defined as 1 in logic, but in the current code, w_CPR would be defined as missing. @robin-wang appreciate your fresh pair of eyes.

The original code: 
https://github.com/wengxyu1030/MICS6/blob/6512b66cc6c75e0f092740152d1b027a918b3fd7/4_sexual_health.do#L21-L47

Please see the draft of the proposed changes (in a separate branch), please note that this is not for final push but for discussion use, where you can see there are some supportive variables/code for examination purposes. https://github.com/wengxyu1030/MICS6/blob/a36557d8489a17363fee9596ac4b4934d6cd746b/4_sexual_health.do#L68-L80

![image](https://user-images.githubusercontent.com/63058112/164949748-e840af87-ab7f-4f2a-8d1b-ef093e6d957d.png)

Definition:
![image](https://user-images.githubusercontent.com/63058112/164950195-3bf669ba-c27b-4e04-ab46-588b5a39101e.png)

**Comment by wengxyu1030** [comment]
**Albania2005**
Definition is correct and consistent with code:

		if inlist(country_name,"Albania2005") {
			global cp3 "cp3a cp3b cp3c cp3e cp3g cp3i cp3k"			// list of modern methods
		}

![image](https://user-images.githubusercontent.com/63058112/164952611-3bde98d2-1d5c-4e0c-a3d6-e2d01f723666.png)

**Comment by wengxyu1030** [comment]
**Ukraine2005**
Definition is correct and consistent with code:
![image](https://user-images.githubusercontent.com/63058112/164952719-e7b65fd4-2cae-47b8-9fdf-03a2d89d447f.png)

		if inlist(country_name,"SierraLeone2005","Suriname2006","Syria2006","Tajikistan2005","Togo2006","TrinidadTobago2006","Ukraine2005") {		// same as above
			global cp3 "cp3a cp3b cp3c cp3d cp3e cp3f cp3g cp3h cp3i cp3j cp3k" 			// list of modern methods

**Comment by robin-wang** [comment]
> https://github.com/wengxyu1030/MICS6/blob/a36557d8489a17363fee9596ac4b4934d6cd746b/4_sexual_health.do#L68-L80

Great catch there. I see your point!
Indeed the old code depends on the order, or the very last variable contained in the CP4 global list.
New logic looks great!

**Comment by wengxyu1030** [comment]
> > https://github.com/wengxyu1030/MICS6/blob/a36557d8489a17363fee9596ac4b4934d6cd746b/4_sexual_health.do#L68-L80
> 
> Great catch there. I see your point! Indeed the old code depends on the order, or the very last variable contained in the CP4 global list. New logic looks great!

Thanks for the confirm, but the result is very different with the DHS trend, further discussion needed with the TTL.

**Comment by wengxyu1030** [comment]
**Albania**

Though the time trend is wired, it's consistent with HEFPI. 

I double-checked the DHS coding (2008) is fine. For MICS, the coding needs discussion @robin-wang : 

- For MICS3 (2005), if using the new logic https://github.com/wengxyu1030/MICS6/blob/a36557d8489a17363fee9596ac4b4934d6cd746b/4_sexual_health.do#L68-L80, the value is much higher, around 54%. 
- For MICS2  (2000), though it's not using loop, the missing value is applied as long as one of the methods is coded missing.  The logic seems not making sense  : https://github.com/Data-Whale-DC/WB-HEFPI-MICS2/blob/7a0ae44f1c53606dfab96d635ba2f7fdb4841d33/MICS2_do_w_reproductive.do#L62-L74

![image](https://user-images.githubusercontent.com/63058112/164997686-e3a47be1-7e22-41f1-b81c-ebd23f6ec97f.png)

**Comment by robin-wang** [comment]
> **Albania**
> 
> Though the time trend is wired, it's consistent with HEFPI.
> 
> I double-checked the DHS coding (2008) is fine. For MICS, the coding needs discussion @robin-wang :
> 
> * For MICS3 (2005), if using the new logic https://github.com/wengxyu1030/MICS6/blob/a36557d8489a17363fee9596ac4b4934d6cd746b/4_sexual_health.do#L68-L80, the value is much higher, around 54%.
> * For MICS2  (2000), though it's not using loop, the missing value is applied as long as one of the methods is coded missing.  The logic seems not making sense  : https://github.com/Data-Whale-DC/WB-HEFPI-MICS2/blob/7a0ae44f1c53606dfab96d635ba2f7fdb4841d33/MICS2_do_w_reproductive.do#L62-L74
> 
> ![image](https://user-images.githubusercontent.com/63058112/164997686-e3a47be1-7e22-41f1-b81c-ebd23f6ec97f.png)

- I checked statcompiler as well. For the two DHS data points, we have correct values.
- MICS2, the code was sooooo weird ..... my god.... gonna raise this with Sven.
- MICS3 will take a look and update on what I found

**Comment by robin-wang** [comment]
@wengxyu1030 
On Albania,
reported value for MICS3 2005 is 22.4%, up from 8% in MICS2 2000

Do you think we might have a smaller denominator that results in high indicator value?

**Comment by wengxyu1030** [comment]
> @wengxyu1030 On Albania, reported value for MICS3 2005 is 22.4%, up from 8% in MICS2 2000
> 
> Do you think we might have a smaller denominator that results in high indicator value?

@robin-wang the denominator is women age 15-49 married or in union, same with the report condition (see screenshot below): 
![image](https://user-images.githubusercontent.com/63058112/165416444-35b2e2b7-ed38-4ce7-a57e-22f545e88459.png)

**Comment by wengxyu1030** [comment]
**Mozambique**
Consistent with the hefpi data, except for AIS is missing benchmark.
![image](https://user-images.githubusercontent.com/63058112/165417576-f4c223f8-2f39-4f83-8146-b7712251da89.png)

**Comment by robin-wang** [comment]
@wengxyu1030 
Methodology update per discussion with Sven

"if any modern method is 1, then 1. if doing rowtotal, be wary of value 9 or 97 or the like."

**Comment by robin-wang** [comment]
In AW's proposed solution, egen rowtotal, missing 
the missing option is dropped, for we retrieve the positive values to affirm wherever appropriate.

**Comment by wengxyu1030** [comment]
> In AW's proposed solution, egen rowtotal, missing the missing option is dropped, for we retrieve the positive values to affirm wherever appropriate.

@robin-wang Thanks for the comment. Could you link the updated branch/commit here so we are on the same page of the meaning of "the mission option is dropped"?

**Comment by wengxyu1030** [comment]
@robin-wang I have adjusted the branch that corrected the code to the latest version https://github.com/wengxyu1030/MICS6/blob/f5684ab943a26d0907ffb3c2caf59a3d9488f2d2/4_sexual_health.do#L68-L83, and the results are now consistent. I will update all the waves accordingly and let you know when the update is completed.

**Comment by robin-wang** [comment]
Hi @wengxyu1030 
Thanks for the update!
On 			egen temp_cp4_tot = rowtotal($cp4) if w_CPR == 0,mi
I have some thoughts, not sure if we keep the [,mi] 

My code below, I propose to remove generating missing values; further, values ? and 97 and the like are removed in my version. Happy to discuss : )

<img width="808" alt="Screenshot 2022-05-03 at 5 14 06 PM" src="https://user-images.githubusercontent.com/32467176/166429659-e7b79f20-6784-4ef9-8f15-6116f5a7d4ec.png">
