### ISSUE TITLE
Added variable consistency

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#6]
![image](https://user-images.githubusercontent.com/63058112/145704166-4f816c40-a52a-4b62-b0cf-22e2e43402a0.png)

There's inconsistency on DHS recodes on c_stunted related variables. @robin-wang is currently taking care of this updating the latest micrcdata into the shared OneDrive folder, below is the progress tracking:

- [x] VII
- [x] VI
- [x] V
- [x] IV
- [x] III
- [x] II
- [x] I

**Comment by robin-wang** [comment]
India2015 is done, thanks to @yixinluo304 , which concludes the data consistency check
