### ISSUE TITLE
Update the Sample weight

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#7]
There's issue with sample weight consistency in earlier waves in MICS:
the c_sampleweight should be generated from chweight
the w_sampleweight should be generated from wmweight

@robin-wang is taking care of it, please use the checklist below to keep track of the progress:

- [x] MICS5
- [x] MICS4
- [x] MICS3
- [x] MICS2

**Comment by robin-wang** [comment]
Updated and Uploaded
