### ISSUE TITLE
Add MIS and AIS data to the DHS time-series

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#9]
Dear @yixinluo304 , thanks for consolidating all the MICS and DHS microdata to the time series. The next task is to integrate MIS and AIS produced microdata into the time series. Luckily these microdata are following the same structure with the DHS produced microdata. So you can directly adjust the code for DHS related dofiles to integrate them. 

Thanks to @robin-wang, he has updated the MIS and AIS survey produced microdata in the shared folder. 

You should be able to find them in the [shared folder:](https://worldbankgroup-my.sharepoint.com/:f:/r/personal/sneelsen_worldbank_org/Documents/Projects/UHC/04%20STC/Haozheyi/World%20Bank/MEASURE%20UHC%20DATA/STATA/DATA/SC/ADePT%20READY/MICS?csf=1&web=1&e=gCGSWC)

![image](https://user-images.githubusercontent.com/63058112/148024390-6ead87b6-df2b-484b-b403-fe2c32a36a87.png)

To add these data to the time series. Please add the subfolder name AIS and MIS in the command below https://github.com/wengxyu1030/UHC-Time-Trend/blob/6a6a4f5f74ad77e5bf938a673107fa859853250c/01_time_trend_DW_DHS.do#L43

And to add the general pattern for the MIS AIS indicators in the command for example Indicator_MIS* Indicator_AIS*
https://github.com/wengxyu1030/UHC-Time-Trend/blob/6a6a4f5f74ad77e5bf938a673107fa859853250c/02_time_trend_DW_DHS.do#L61

Lastly, you can generate surveyid by conditional on the variable survey value on the command:
https://github.com/wengxyu1030/UHC-Time-Trend/blob/6a6a4f5f74ad77e5bf938a673107fa859853250c/02_time_trend_DW_DHS.do#L101

Please let me know if you can successfully integrate these two sets of data set into the time series. Please work on a new branch based on what's in the main branch. 

Thanks again, please don't hesitate to ask if there's any questions. 👍

**Comment by yixinluo304** [comment]
Dear @wengxyu1030,

Thanks for your help～I have already integrated the AIS&MIS data set into the time series and added a few lines to generate surveyid by conditional #https://github.com/wengxyu1030/UHC-Time-Trend/pull/10. Could you please help to see if there are any problems with the pull request code?

Best Regards💗

**Comment by wengxyu1030** [comment]
Thanks @yixinluo304 , you did a great job! I have reviewed and there's no problem with the code. I will rerun on my end to test and update the output in the shared folders.
